### PR TITLE
Bugfix: log levels in log.go + add regression test

### PR DESCRIPTION
**Pull request by johanlunds**
The log levels didn't work.

Nice work with the New Relic packages btw!

### CODE REVIEW

**Comment by johanlunds** [comment]
Go 1.2 build seems to be failing. It doesn't seem like it's anything introduced in this PR.

**Comment by johanlunds** [comment]
ping @neocortical. Any chance of getting this in? Do you want me to do any changes?

**Comment by neocortical** [comment]
Sorry, Johan, I didn't see the email.

Thanks for catching my silly mistake!

Cheers,
nate

**Comment by johanlunds** [comment]
Thanks! 👍

**Pull request merged**
